require ("converttoupper")
require ("addTwonum")
require ("addManynum")
require ("compRannum")
require ("evenOdd")
--print(changeToupper())
--printuppercase()
--printTwonumsum()
--printusersum()
--printRandomnum()